package com.sigeu.model;

/**
 * Response body returned by POST /emergency.
 * Tells the frontend which entity is assigned and the priority level.
 */
public class EmergencyResponse {

    /** Assigned entity: "Hospital", "Policía" or "Bomberos" */
    private String entity;

    /** Priority level: "Alta", "Media" or "Baja" */
    private String priority;

    /** Human-readable message in Spanish for the citizen */
    private String message;

    /** Echo of the received emergency type */
    private String type;

    /** Unique report ID generated by the backend */
    private String reportId;

    // ── Constructor ──

    public EmergencyResponse(String entity, String priority, String message,
                              String type, String reportId) {
        this.entity   = entity;
        this.priority = priority;
        this.message  = message;
        this.type     = type;
        this.reportId = reportId;
    }

    // ── Getters ──

    public String getEntity()   { return entity; }
    public String getPriority() { return priority; }
    public String getMessage()  { return message; }
    public String getType()     { return type; }
    public String getReportId() { return reportId; }
}
